spring.application.name=employeemanagement

spring.datasource.url=jdbc:oracle:thin:@ora-02.db.lab.etf.unsa.ba:1521:ETFDB
spring.datasource.username=NBPT9
spring.datasource.password=nbpt9
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=NBPT9
spring.liquibase.enabled=true

server.port=8080

jwt.secret=yourSecretKeyForJWTGeneration
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Swagger UI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Optionally, customize title and description
springdoc.swagger-ui.title=Employee Management API Docs
springdoc.swagger-ui.description=Interactive documentation for all REST endpoints
