--liquibase formatted sql

--changeset amar:001
CREATE TABLE NBPT9.EMPLOYEE_BACKUP AS SELECT * FROM NBPT9.EMPLOYEE WHERE 1=0;
ALTER TABLE NBPT9.EMPLOYEE_BACKUP ADD BACKED_UP_AT TIMESTAMP DEFAULT SYSTIMESTAMP;

CREATE TABLE NBPT9.EMPLOYMENT_BACKUP AS SELECT * FROM NBPT9.EMPLOYMENT WHERE 1=0;
ALTER TABLE NBPT9.EMPLOYMENT_BACKUP ADD BACKED_UP_AT TIMESTAMP DEFAULT SYSTIMESTAMP;

CREATE TABLE NBPT9.VEHICLE_BACKUP AS SELECT * FROM NBPT9.VEHICLE WHERE 1=0;
ALTER TABLE NBPT9.VEHICLE_BACKUP ADD BACKED_UP_AT TIMESTAMP DEFAULT SYSTIMESTAMP;
--rollback DROP TABLE NBPT9.EMPLOYEE_BACKUP;
--rollback DROP TABLE NBPT9.EMPLOYMENT_BACKUP;
--rollback DROP TABLE NBPT9.VEHICLE_BACKUP;