--liquibase formatted sql

--changeset amar:001
CREATE OR REPLACE PROCEDURE NBPT9.RUN_DAILY_BACKUP AS
BEGIN
DELETE FROM NBPT9.EMPLOYEE_BACKUP;
DELETE FROM NBPT9.EMPLOYMENT_BACKUP;
DELETE FROM NBPT9.VEHICLE_BACKUP;

INSERT INTO NBPT9.EMPLOYEE_BACKUP
SELECT e.*, SYSTIMESTAMP FROM NBPT9.EMPLOYEE e;
INSERT INTO NBPT9.EMPLOYMENT_BACKUP
SELECT e.*, SYSTIMESTAMP FROM NBPT9.EMPLOYMENT e;
INSERT INTO NBPT9.VEHICLE_BACKUP
SELECT v.*, SYSTIMESTAMP FROM NBPT9.VEHICLE v;

COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RUN_DAILY_BACKUP;
/

--changeset amar:backup-scheduler dbms:oracle endDelimiter:/
BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'NBPT9.DAILY_TABLE_BACKUP',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'NBPT9.RUN_DAILY_BACKUP',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY; BYHOUR=3; BYMINUTE=0; BYSECOND=0',
        enabled         => TRUE,
        comments        => 'Daily backup of EMPLOYEE, EMPLOYMENT, VEHICLE'
    );
END;
/
--rollback BEGIN DBMS_SCHEDULER.DROP_JOB('NBPT9.DAILY_TABLE_BACKUP'); END;