-- liquibase formatted sql

-- changeset ahmed:007
CREATE TABLE department (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    description VARCHAR2(255)
);

-- changeset ahmed:016
ALTER TABLE department ADD CONSTRAINT UNIQUE_DEPARTMENT_NAME UNIQUE (name);
