--liquibase formatted sql

--changeset edna:014
CREATE TABLE disability (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    disability_type VARCHAR2(100),
    disability_level VARCHAR2(100),
    description VARCHAR2(255),
    registered_date DATE
);

ALTER TABLE disability
    ADD CONSTRAINT FK_DISABILITY_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES employee(id);
