--liquibase formatted sql

--changeset bakir:009
CREATE TABLE emergency_contact (
                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   employee_id NUMBER NOT NULL,
                                   first_name VARCHAR2(100),
                                   last_name VARCHAR2(100),
                                   relationship VARCHAR2(100),
                                   phone_number VARCHAR2(50),
                                   email VARCHAR2(100),
                                   address VARCHAR2(255)
);

ALTER TABLE emergency_contact
    ADD CONSTRAINT FK_EMERGENCY_CONTACT_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES employee(id);