--liquibase formatted sql

--changeset ahmed:020
CREATE TABLE EMPLOYEE_PHOTO (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL UNIQUE,
    PHOTO BLOB NOT NULL,
    CONTENT_TYPE VARCHAR2(100) DEFAULT 'application/octet-stream' NOT NULL,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE EMPLOYEE_PHOTO
    ADD CONSTRAINT FK_EMPLOYEE_PHOTO_USER
        FOREIGN KEY (USER_ID)
            REFERENCES NBP.NBP_USER(ID);

CREATE SEQUENCE EMPLOYEE_PHOTO_SEQ START WITH 1 INCREMENT BY 1;


