--liquibase formatted sql

--changeset bakir:010
CREATE TABLE family_member (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               employee_id NUMBER NOT NULL,
                               first_name VARCHAR2(100),
                               last_name VARCHAR2(100),
                               relation VARCHAR2(100),
                               date_of_birth DATE,
                               dependent NUMBER(1),
                               occupation VARCHAR2(100)
);

ALTER TABLE family_member
    ADD CONSTRAINT FK_FAMILY_MEMBER_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES employee(id);