--liquibase formatted sql

--changeset edna:011
CREATE TABLE finance (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    bank_name VARCHAR2(255),
    bank_account_number VARCHAR2(255),
    iban VARCHAR2(255),
    tax_number VARCHAR2(255),
    salary NUMBER,
    currency VARCHAR2(50),
    payment_frequency VARCHAR2(100),
    bonus_eligible NUMBER
);

ALTER TABLE finance
    ADD CONSTRAINT FK_FINANCE_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES employee(id);
