-- liquibase formatted sql

-- changeset ahmed:005
CREATE TABLE holiday (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_name VARCHAR2(255),
    holiday_date DATE,
    country VARCHAR2(255),
    description VARCHAR2(255)
);

