--liquibase formatted sql

--changeset bakir:008
CREATE TABLE personal_contact (
                                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  employee_id NUMBER NOT NULL,
                                  phone_number VARCHAR2(50),
                                  personal_email VARCHAR2(100)
);

ALTER TABLE personal_contact
    ADD CONSTRAINT FK_PERSONAL_CONTACT_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES employee(id);