--liquibase formatted sql

--changeset ahmed:015
INSERT INTO NBP.NBP_ROLE (NAME)
SELECT 'EMS_ADMINISTRATOR' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NBP.NBP_ROLE WHERE NAME = 'EMS_ADMINISTRATOR');

INSERT INTO NBP.NBP_ROLE (NAME)
SELECT 'EMS_MANAGER' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NBP.NBP_ROLE WHERE NAME = 'EMS_MANAGER');

INSERT INTO NBP.NBP_ROLE (NAME)
SELECT 'EMS_EMPLOYEE' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NBP.NBP_ROLE WHERE NAME = 'EMS_EMPLOYEE');
