--liquibase formatted sql

--changeset nejra:trigger-001 splitStatements:false
CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON NBPT9.EMPLOYEE
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSIF DELETING THEN v_action := 'DELETE';
    END IF;
    INSERT INTO NBP.NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_ID_SEQ.NEXTVAL, v_action, 'EMPLOYEE', SYSTIMESTAMP, USER);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

--changeset nejra:trigger-002 splitStatements:false
CREATE OR REPLACE TRIGGER TRG_DEPARTMENT_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON NBPT9.DEPARTMENT
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSIF DELETING THEN v_action := 'DELETE';
    END IF;
    INSERT INTO NBP.NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_ID_SEQ.NEXTVAL, v_action, 'DEPARTMENT', SYSTIMESTAMP, USER);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

--changeset nejra:trigger-003 splitStatements:false
CREATE OR REPLACE TRIGGER TRG_EMPLOYMENT_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON NBPT9.EMPLOYMENT
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSIF DELETING THEN v_action := 'DELETE';
    END IF;
    INSERT INTO NBP.NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_ID_SEQ.NEXTVAL, v_action, 'EMPLOYMENT', SYSTIMESTAMP, USER);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

--changeset nejra:trigger-004 splitStatements:false
CREATE OR REPLACE TRIGGER TRG_ADDRESS_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON NBPT9.ADDRESS
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSIF DELETING THEN v_action := 'DELETE';
    END IF;
    INSERT INTO NBP.NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_ID_SEQ.NEXTVAL, v_action, 'ADDRESS', SYSTIMESTAMP, USER);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

--changeset nejra:trigger-005 splitStatements:false
CREATE OR REPLACE TRIGGER TRG_VACATION_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON NBPT9.VACATION
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSIF DELETING THEN v_action := 'DELETE';
    END IF;
    INSERT INTO NBP.NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_ID_SEQ.NEXTVAL, v_action, 'VACATION', SYSTIMESTAMP, USER);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

--changeset nejra:trigger-006 splitStatements:false
CREATE OR REPLACE TRIGGER TRG_HOLIDAY_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON NBPT9.HOLIDAY
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(10);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSIF DELETING THEN v_action := 'DELETE';
    END IF;
    INSERT INTO NBP.NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_ID_SEQ.NEXTVAL, v_action, 'HOLIDAY', SYSTIMESTAMP, USER);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

--rollback DROP TRIGGER TRG_EMPLOYEE_AUDIT;
--rollback DROP TRIGGER TRG_DEPARTMENT_AUDIT;
--rollback DROP TRIGGER TRG_EMPLOYMENT_AUDIT;
--rollback DROP TRIGGER TRG_ADDRESS_AUDIT;
--rollback DROP TRIGGER TRG_VACATION_AUDIT;
--rollback DROP TRIGGER TRG_HOLIDAY_AUDIT;
