-- liquibase formatted sql

-- changeset ahmed:006
CREATE TABLE vacation (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER,
    start_date DATE,
    end_date DATE,
    vacation_type VARCHAR2(255),
    status VARCHAR2(255),
    approved_by NUMBER,
    reason VARCHAR2(255)
);

ALTER TABLE vacation
    ADD CONSTRAINT FK_VACATION_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES EMPLOYEE(ID);

ALTER TABLE vacation
    ADD CONSTRAINT FK_VACATION_APPROVED_BY
        FOREIGN KEY (approved_by)
            REFERENCES EMPLOYEE(ID);
