--liquibase formatted sql

--changeset edna:012
CREATE TABLE vehicle (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    vehicle_make VARCHAR2(100),
    vehicle_model VARCHAR2(100),
    license_plate VARCHAR2(50),
    vin_number VARCHAR2(100),
    fuel_type VARCHAR2(50),
    vehicle_type VARCHAR2(50),
    assigned_date DATE,
    return_date DATE
);

ALTER TABLE vehicle
    ADD CONSTRAINT FK_VEHICLE_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES employee(id);
