--liquibase formatted sql

--changeset edna:013
CREATE TABLE work_permit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    permit_number VARCHAR2(100),
    permit_type VARCHAR2(100),
    issuing_country VARCHAR2(100),
    issue_date DATE,
    expiry_date DATE,
    status VARCHAR2(100)
);

ALTER TABLE work_permit
    ADD CONSTRAINT FK_WORK_PERMIT_EMPLOYEE
        FOREIGN KEY (employee_id)
            REFERENCES employee(id);
